package api.gommo._root.comum.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NonNull;

import java.util.List;
import java.util.stream.Stream;

@Getter
@AllArgsConstructor
public enum ModuloENUM {

    GESTAO_ADMISSAO("GESTAO_ADMISSAO", SistemaENUM.DEPARTAMENTO_PESSOAL),
    GESTAO_AFASTAMENTO("GESTAO_AFASTAMENTO", SistemaENUM.DEPARTAMENTO_PESSOAL),
    GESTAO_DEPARTAMENTO("GESTAO_DEPARTAMENTO", SistemaENUM.DEPARTAMENTO_PESSOAL),
    GESTAO_EMPRESA("GESTAO_EMPRESA", SistemaENUM.DEPARTAMENTO_PESSOAL),
    GESTAO_PERFIL("GESTAO_PERFIL", SistemaENUM.DEPARTAMENTO_PESSOAL),
    GESTAO_USUARIO("GESTAO_USUARIO", SistemaENUM.DEPARTAMENTO_PESSOAL),
    GESTAO_LOCALIDADE("GESTAO_LOCALIDADE", SistemaENUM.DEPARTAMENTO_PESSOAL),
    GESTAO_FERIAS("GESTAO_FERIAS", SistemaENUM.DEPARTAMENTO_PESSOAL),
    GESTAO_DESLIGAMENTO("GESTAO_DESLIGAMENTO", SistemaENUM.DEPARTAMENTO_PESSOAL),
    GESTAO_COLABORADORES_ATIVOS("GESTAO_COLABORADORES_ATIVOS", SistemaENUM.DEPARTAMENTO_PESSOAL),
    GESTAO_COLABORADORES_INATIVOS("GESTAO_COLABORADORES_INATIVOS", SistemaENUM.DEPARTAMENTO_PESSOAL),
    GESTAO_LANCAMENTOS("GESTAO_LANCAMENTOS", SistemaENUM.DEPARTAMENTO_PESSOAL),
    GESTAO_EVENTOS("GESTAO_EVENTOS", SistemaENUM.DEPARTAMENTO_PESSOAL),
    GESTAO_CONTRA_CHEQUE("GESTAO_CONTRA_CHEQUE", SistemaENUM.DEPARTAMENTO_PESSOAL),
    GESTAO_REGISTRO_DE_PONTO("GESTAO_REGISTRO_DE_PONTO", SistemaENUM.DEPARTAMENTO_PESSOAL),
    GESTAO_JORNADAS("GESTAO_JORNADAS", SistemaENUM.DEPARTAMENTO_PESSOAL),
    GESTAO_ESCALAS("GESTAO_ESCALAS", SistemaENUM.DEPARTAMENTO_PESSOAL),
    GESTAO_VALE_TRANSPORTE("GESTAO_VALE_TRANSPORTE", SistemaENUM.DEPARTAMENTO_PESSOAL),
    GESTAO_VALE_ALIMENTACAO("GESTAO_VALE_ALIMENTACAO", SistemaENUM.DEPARTAMENTO_PESSOAL),
    GESTAO_PLANO_SAUDE("GESTAO_PLANO_SAUDE", SistemaENUM.DEPARTAMENTO_PESSOAL),
    GESTAO_CONVENIOS("GESTAO_CONVENIOS", SistemaENUM.DEPARTAMENTO_PESSOAL),
    GESTAO_RESCISOES("GESTAO_RESCISOES", SistemaENUM.DEPARTAMENTO_PESSOAL),
    GESTAO_CARGOS("GESTAO_CARGOS", SistemaENUM.DEPARTAMENTO_PESSOAL),
    GESTAO_DEPARTAMENTOS("GESTAO_DEPARTAMENTOS", SistemaENUM.DEPARTAMENTO_PESSOAL),
    GESTAO_SETORES("GESTAO_SETORES", SistemaENUM.DEPARTAMENTO_PESSOAL),
    GESTAO_CONTRATO("GESTAO_CONTRATO", SistemaENUM.DEPARTAMENTO_PESSOAL),
    GESTAO_CARGA_HORARIA("GESTAO_CARGA_HORARIA", SistemaENUM.DEPARTAMENTO_PESSOAL),
    GESTAO_CURSOS("GESTAO_CURSOS", SistemaENUM.DEPARTAMENTO_PESSOAL),
    GESTAO_AVALIACOES_DESEMPENHO("GESTAO_AVALIACOES_DESEMPENHO", SistemaENUM.DEPARTAMENTO_PESSOAL),
    GESTAO_PLANO_CARREIRA("GESTAO_PLANO_CARREIRA", SistemaENUM.DEPARTAMENTO_PESSOAL),
    GESTAO_VAGAS("GESTAO_VAGAS", SistemaENUM.DEPARTAMENTO_PESSOAL),
    GESTAO_SELECAO_CANDIDATOS("GESTAO_SELECAO_CANDIDATOS", SistemaENUM.DEPARTAMENTO_PESSOAL),
    GESTAO_PROCESSOS_SELETIVOS("GESTAO_PROCESSOS_SELETIVOS", SistemaENUM.DEPARTAMENTO_PESSOAL)
    ;

    @NonNull
    private final String key;

    @NonNull
    private final SistemaENUM sistema;

    public static List<ModuloENUM> getModulosPorSistema(SistemaENUM sistema) {
        return Stream.of(ModuloENUM.values())
                .filter(modulo -> modulo.getSistema().equals(sistema))
                .toList();
    }
}
