CREATE ROLE tamarin WITH LOGIN PASSWORD '68e75b69-7e51-4a51-867d-59de61566c75' CREATEDB CREATEROLE REPLICATION;
GRANT ALL PRIVILEGES ON DATABASE tamarin TO tamarin;

-- Permissões em todas as tabelas existentes
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO tamarin;

-- Permissões em todas as sequências (se houver autoincrementos)
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO tamarin;

-- Permissões em todas as funções
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO tamarin;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO tamarin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO tamarin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO tamarin;